/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArchivedDay { 'date' : string, 'archivedAt' : bigint }
export interface TimetableEntry {
  'id' : string,
  'startTime' : string,
  'endTime' : string,
  'date' : string,
  'taskName' : string,
  'colorTag' : string,
  'notes' : string,
  'priority' : string,
}
export interface _SERVICE {
  'addEntry' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    undefined
  >,
  'archiveDay' : ActorMethod<[string], undefined>,
  'deleteEntry' : ActorMethod<[string], undefined>,
  'getAllEntryDates' : ActorMethod<[], Array<string>>,
  'getArchivedDaysWithinYear' : ActorMethod<[], Array<ArchivedDay>>,
  'getEntriesForDate' : ActorMethod<[string], Array<TimetableEntry>>,
  'unarchiveDay' : ActorMethod<[string], undefined>,
  'updateEntry' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];