/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ArchivedDay = IDL.Record({
  'date' : IDL.Text,
  'archivedAt' : IDL.Int,
});
export const TimetableEntry = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'date' : IDL.Text,
  'taskName' : IDL.Text,
  'colorTag' : IDL.Text,
  'notes' : IDL.Text,
  'priority' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'archiveDay' : IDL.Func([IDL.Text], [], []),
  'deleteEntry' : IDL.Func([IDL.Text], [], []),
  'getAllEntryDates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getArchivedDaysWithinYear' : IDL.Func([], [IDL.Vec(ArchivedDay)], ['query']),
  'getEntriesForDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TimetableEntry)],
      ['query'],
    ),
  'unarchiveDay' : IDL.Func([IDL.Text], [], []),
  'updateEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ArchivedDay = IDL.Record({ 'date' : IDL.Text, 'archivedAt' : IDL.Int });
  const TimetableEntry = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'date' : IDL.Text,
    'taskName' : IDL.Text,
    'colorTag' : IDL.Text,
    'notes' : IDL.Text,
    'priority' : IDL.Text,
  });
  
  return IDL.Service({
    'addEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'archiveDay' : IDL.Func([IDL.Text], [], []),
    'deleteEntry' : IDL.Func([IDL.Text], [], []),
    'getAllEntryDates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getArchivedDaysWithinYear' : IDL.Func(
        [],
        [IDL.Vec(ArchivedDay)],
        ['query'],
      ),
    'getEntriesForDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TimetableEntry)],
        ['query'],
      ),
    'unarchiveDay' : IDL.Func([IDL.Text], [], []),
    'updateEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };